# Generated by Django 3.1.5 on 2021-01-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150, verbose_name='Text')),
                ('is_complited', models.BooleanField(verbose_name='Is Complited')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='CreatedAt')),
            ],
        ),
    ]
