# Generated by Django 3.1.5 on 2021-01-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_complited',
        ),
        migrations.AddField(
            model_name='task',
            name='complited',
            field=models.BooleanField(default=False, verbose_name='Is Complited'),
        ),
    ]
