# Generated by Django 3.1.5 on 2021-01-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210108_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complited',
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Is Completed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
    ]
