# Generated by Django 3.1.5 on 2021-01-08 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210108_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
